backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Descrição", name: "body", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image" }
