backend:
  name: git-gateway
  branch: main

media_folder: "imagens/uploads"
public_folder: "/imagens/uploads"

collections:
  - name: "materiais"
    label: "Materiais Pedagógicos"
    folder: "materiais"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Arquivo", name: "file", widget: "file" }
